# Generated by Django 4.0.5 on 2022-06-21 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaxs', models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], max_length=20)),
                ('full_name', models.CharField(max_length=100, verbose_name='Toliq isim')),
                ('number', models.IntegerField()),
                ('name_of_company', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('yangi', 'Yangi'), ('tasdiqlangan', 'Tasdiqlamgan'), ('moderatsiyada', 'Moderatsiyada'), ('bekor qilingan', 'Bekor Qilingan')], max_length=20)),
            ],
            options={
                'verbose_name': 'Homiylar',
                'verbose_name_plural': 'Homiylar',
            },
        ),
        migrations.CreateModel(
            name='SponsorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('name_of_company', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ariza Formasi',
                'verbose_name_plural': 'Ariza Formasi',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=datetime.date(2022, 6, 21))),
                ('full_name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('university', models.CharField(choices=[('O’zbekiston milliy universiteti', 'O’zbekiston milliy universiteti'), ('Toshkent davlat texnika universiteti', 'Toshkent davlat texnika universiteti'), ('Toshkent davlat iqtisodiyot universiteti', 'Toshkent davlat iqtisodiyot universiteti'), ('O’zbekiston davlat jahon tillari universiteti', 'O’zbekiston davlat jahon tillari universiteti'), ('Toshkent davlat sharqshunoslik instituti', 'Toshkent davlat sharqshunoslik instituti')], max_length=150)),
                ('major', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistratura', 'Magistratura'), ('aspirantura', 'Aspirantura')], max_length=50)),
                ('demand', models.IntegerField()),
                ('paid_money', models.IntegerField()),
                ('sponsors', models.ManyToManyField(to='users.sponsor', verbose_name='Sponsors of Students')),
            ],
            options={
                'verbose_name': "O'quvchilar",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
    ]
