# Generated by Django 4.0.5 on 2022-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(to='users.sponsor'),
        ),
    ]
