# Generated by Django 4.0.5 on 2022-06-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_universitymodel_alter_student_university'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsorApplication',
            new_name='SponsorApplicationModel',
        ),
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='SponsorModel',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentModel',
        ),
    ]
