# Generated by Django 4.0.5 on 2022-06-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_sponsors_student_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=datetime.date(2022, 6, 19)),
        ),
    ]
