# Generated by Django 4.0.5 on 2022-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_sponsorapplication_sponsorapplicationmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsormodel',
            old_name='shaxs',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
