# Generated by Django 4.0.5 on 2022-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_shaxs_sponsormodel_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplicationmodel',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
