# Generated by Django 4.0.5 on 2022-06-21 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_sponsorapplicationmodel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplicationmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='sponsorapplicationmodel',
            name='name_of_company',
            field=models.CharField(max_length=100, verbose_name='Firma/Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='sponsorapplicationmodel',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='sponsorapplicationmodel',
            name='person',
            field=models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], max_length=20, verbose_name='Shaxs'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='condition',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('tasdiqlangan', 'Tasdiqlamgan'), ('moderatsiyada', 'Moderatsiyada'), ('bekor qilingan', 'Bekor Qilingan')], max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='name_of_company',
            field=models.CharField(max_length=100, verbose_name='Firma/Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Telefon Raqam'),
        ),
        migrations.AlterField(
            model_name='sponsormodel',
            name='person',
            field=models.CharField(choices=[('yuridik', 'Yuridik'), ('jismoniy', 'Jismoniy')], max_length=20, verbose_name='Shaxs'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='demand',
            field=models.IntegerField(verbose_name='Soralgan pull miqdori'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='major',
            field=models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistratura', 'Magistratura'), ('aspirantura', 'Aspirantura')], max_length=50, verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='number',
            field=models.IntegerField(verbose_name='Telefon Raqam'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='paid_money',
            field=models.IntegerField(verbose_name="To'langan pull miqdori"),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(upload_to=datetime.date(2022, 6, 21), verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='sponsors',
            field=models.ManyToManyField(to='users.sponsormodel', verbose_name='Homiy'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.universitymodel', verbose_name='Institut'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='name_of_university',
            field=models.CharField(max_length=250, verbose_name='Universtitetning Nomi'),
        ),
    ]
