# Generated by Django 4.0.5 on 2022-06-22 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_sponsorapplicationmodel_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=datetime.date(2022, 6, 22), verbose_name='Rasim')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('number', models.IntegerField(verbose_name='Telefon Raqam')),
                ('major', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistratura', 'Magistratura'), ('aspirantura', 'Aspirantura')], max_length=50, verbose_name="Yo'nalish")),
                ('demand', models.IntegerField(verbose_name='Soralgan pull miqdori')),
                ('paid_money', models.IntegerField(verbose_name="To'langan pull miqdori")),
            ],
            options={
                'verbose_name': "O'quvchilar",
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.DeleteModel(
            name='SponsorApplicationModel',
        ),
        migrations.RenameModel(
            old_name='SponsorModel',
            new_name='Sponsor',
        ),
        migrations.RenameModel(
            old_name='UniversityModel',
            new_name='University',
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(to='users.sponsor', verbose_name='Homiy'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.university', verbose_name='Institut'),
        ),
    ]
