# Generated by Django 4.0.5 on 2022-06-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_delete_sponsorapplicationmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name_of_university',
            new_name='university_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sponsors',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlamgan'), (3, 'Moderatsiyada'), (4, 'Bekor Qilingan')], verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name_of_company',
            field=models.CharField(max_length=250, verbose_name='Firma/Kompaniya nomi'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='number',
            field=models.CharField(max_length=250, verbose_name='Telefon Raqam'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='person',
            field=models.IntegerField(choices=[(1, 'Yuridik'), (2, 'Jismoniy')], verbose_name='Shaxs turi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistratura'), (3, 'Aspirantura')], verbose_name='Talim turi'),
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='Pull miqdori')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Talaba vs Homiy',
                'verbose_name_plural': 'Talaba va Homiylar',
            },
        ),
    ]
