# Generated by Django 4.0.5 on 2022-06-23 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_sponsor_created_by_alter_student_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='university',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=datetime.date(2022, 6, 23), verbose_name='Rasim'),
        ),
    ]
