# Generated by Django 4.0.5 on 2022-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_sponsor_created_by_remove_student_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
