# Generated by Django 4.0.5 on 2022-06-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sponsor_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='paid_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='money',
            field=models.IntegerField(verbose_name="To'langan Pull miqdori"),
        ),
    ]
