# Generated by Django 4.0.5 on 2022-06-30 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_sponsor_paid_money_alter_studentsponsor_money'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Homiy', 'verbose_name_plural': 'Homiylar'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=datetime.date(2022, 6, 30), verbose_name='Rasim'),
        ),
    ]
